version: "3"

services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    container_name: server 
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
